### ISSUE TITLE
Enabling Optimization breaks algorithm code linking

### ISSUE THREAD

**Issue by Ferruck** [ComputationalRadiationPhysics/imresh#14]
In the current `CMakeLists.txt` on the `refactoring` branch (by now the most up to date), no parameters for compiler optimizations are given. This defaults to no optimization (at least on my machine).

When turning on optimization with anything higher than `-O0` (e.g. `-O1`, `-O2` and so on) linking the example binary fails with

```
[100%] Linking CXX executable examples
CMakeFiles/examples.dir/examples/createAtomCluster.cpp.o: In function `examples::createAtomCluster(std::vector<unsigned int, std::allocator<unsigned int> > const&)':
createAtomCluster.cpp:(.text+0xf2): undefined reference to `void imresh::libs::gaussianBlur<float>(float* const&, unsigned int const&, unsigned int const&, double const&)'
createAtomCluster.cpp:(.text+0xd4f): undefined reference to `void imresh::libs::gaussianBlur<float>(float* const&, unsigned int const&, unsigned int const&, double const&)'
libimresh.so: undefined reference to `float imresh::algorithms::vectorMax<float>(float* const&, unsigned int const&)'
libimresh.so: undefined reference to `void imresh::algorithms::cuda::cudaGaussianBlur<float>(float* const&, unsigned int const&, unsigned int const&, double const&)'
libimresh.so: undefined reference to `void imresh::algorithms::applyComplexModulus<float [2], float>(float (* const&) [2], float const (* const&) [2], float const* const&, unsigned int const&)'
libimresh.so: undefined reference to `void imresh::algorithms::complexNormElementwise<float, float [2]>(float* const&, float const (* const&) [2], unsigned int const&)'
collect2: Fehler: ld gab 1 als Ende-Status zurück
```

Right now I have no idea where to start investigating into this. As this is not game breaking at the moment and this is your code, I'd like to ask you, @mxmlnkn to look into this when you have some sparse time. But as this library is intended to be fast, compiler optimizations should be possible at least right before the final release.

Maybe it's just an error in the `CMakeLists.txt` that I don't get right now so the first step could be that you could try your old Makefiles with enabled optimizations.

**Comment by mxmlnkn** [comment]
Another possible solution to this may had have been adding

``` C++
extern "C"
```

This issue becomes relevant again, because alpaka doesn't like explicit template instantiations, see https://github.com/ComputationalRadiationPhysics/alpaka/issues/183#issuecomment-190737087 A solution to the problem in that comment is using a dummy function with `CUPLA_KERNEL` calls, implicitely instantiating only the device version of a kernel, not both, host and device.
